#!/usr/bin/env bash

set -euo pipefail

# Vars
# absolute path to directory containing this script
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
set +x
. "${SCRIPTS_DIR}/../bash-lib/init"
set -x # After bash-lib init
# root of conjur-ecs-deploy repo
CED_ROOT="$(dirname "${SCRIPTS_DIR}")"
# root home dir for the cli container
# auth information will be stored there after login
CLI_ROOT="${CED_ROOT}/cli_root"
CLI_IMAGE="${CLI_IMAGE:-"cyberark/conjur-cli:5"}"
DOMAIN_NAME="${DOMAIN_NAME:-ci.conjur.net}" # Doesn't include this stack's subdomain
ADMIN_PASSWORD_METADATA_FILE="admin_password_meta.json"

# Functions

# Run conjur cli command in docker
dconjur(){
  docker run --rm -i \
    --volume="${CED_ROOT}:/workspace" \
    --volume="${CLI_ROOT}:/root" \
    --workdir="/workspace" \
    "${CLI_IMAGE}" \
    "${@}"
}

check_variable_value(){
  conjur_var="${1}"
  expected_value="${2}"
  retrieved_value="$(dconjur variable value "${conjur_var}")"
  if [[ "${retrieved_value}" != "${expected_value}" ]]; then
    bl_fail "Retrieved value of ${conjur_var} (${retrieved_value}) \
      does not match the value it was set to (${expected_value})"
  else
    echo "Verified the expected value of ${TEST_VAR}: (${expected_value})"
  fi
}

# Retrieve conjur admin password from AWS Secrets Manager
get_admin_password(){
  local ADMIN_PASSWORD_ARN
  # This file created by scripts/prepare
  ADMIN_PASSWORD_ARN="$(jq -r .ARN < "${ADMIN_PASSWORD_METADATA_FILE}" )"
  aws secretsmanager get-secret-value \
    --secret-id "${ADMIN_PASSWORD_ARN}" \
    --output json \
    | jq -r '.SecretString'
}

# Main flow

# Verify Inputs
if [[ -z "${STACK_NAME}" ]]; then
  bl_die "STACK_NAME must be set before running ${0}"
fi
if [[ ! -r "${ADMIN_PASSWORD_METADATA_FILE}" ]];  then
  bl_die "Cannot open file ${ADMIN_PASSWORD_METADATA_FILE}, did you run scripts/prepare?"
fi

mkdir -p "${CLI_ROOT}"

# Configure CLI if not already configured.
if [[ ! -e ${CLI_ROOT}/conjur-conjur.pem ]]; then
  echo -e "yes\nconjur" |dconjur init -u "https://${STACK_NAME}.${DOMAIN_NAME}"
  set +x +o history
  echo "dconjur authn login -u admin -p \"***\""
  dconjur authn login -u admin -p "$(get_admin_password)"
  set -x
  echo "Conjur CLI Configured"
else
  echo "Skipping Conjur CLI configuration as certificate is already present"
fi
